config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "signup", to: "users#new"

  resources :tasks, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :users, only: [:create] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
      before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy, :show, :update, :edit]
  def index
    @tasks = current_user.tasks.order(id: :desc).page(params[:page]).per(10)
    @task = current_user.tasks.build

  end
  def new
    @task = Task.new
  end

def show
end

  def create
      @task = current_user.tasks.build(task_params)
      
      if @task.save
          flash[:success] = "Task　投稿完了"
          redirect_to root_url
      else
        @tasks = current_user.tasks.order(id: :desc).page(params[:page])
          flash.now[:danger] = "Task 投稿失敗"
          render :new
      end
  end

  def edit
  end

  def update
      
      if @task.update(task_params)
          flash[:success] = "Task 更新完了"
          redirect_to root_url
      else
          flash.now[:danger] = "Task 更新失敗"
          render :edit
      end
  end

  def destroy
    @task.destroy

  flash[:success] = 'Task削除'
  redirect_to root_url
  end
  

  private

  # Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status, :user)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)
    
      if @user.save
        flash[:seccess] = "ユーザー登録完了"
        redirect_to root_url
      else
        flash.now[:danger] = "ユーザー登録失敗"
        render :new
      end
  end

  private

  # Strong Parameter
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
    !!current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |flash_type, flash_message| %>
  <div class="alert alert-<%= flash_type %>"><%= flash_message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
    <nav class="navbar navbar-dark bg-dark  navbar-expand-sm nav-tabs">
        <a href="/" class="navbar-brand">TASK LIST <i class="fas fa-tasks"></i></a>


        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">

                <% if logged_in? %>
                <li class="nav-item"><%= link_to 'NewTask', new_task_path, class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
                
                <% else %>
                <li class="nav-item"><%= link_to 'SignUp', signup_path, class: 'nav-link' %></li>
                <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
                <% end %>
            </ul>
        </div>

    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>



<body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
        <%= render 'layouts/flash_messages' %>
        <%= yield %>

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS, then Font Awesome -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
</body>

</html>

app/views/tasks/_form.html.erb
        <div class="card">
            <div class="card-header">
                新規タスク
            </div>
                <div class="card-body">

                    <%= form_with(model: @task, local: true) do |f| %>

                    <% if @task.errors.any? %>
                    <div id="error_explanation" class="alert alert-warning">
                        <ul class="mb-0">
                            <% @task.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                    <% end %>


                    <div class="form-group">
                        <%= f.label :content, "タスク" %>
                        <%= f.text_field :content, class: 'form-control' %>
                    </div>

                    <div class="form-group">
                        <%= f.label :status, "ステータス" %>
                        <%= f.text_field :status, class: 'form-control' %>
                    </div>

                    <%= f.submit '投稿', class: 'btn btn-primary' %>
                    <% end %>

                </div>
        </div>

app/views/tasks/_tasks.html.erb
<ul class="list-unstyled">
    <% @tasks.each do |task| %>
    <li class="media mb-3">
        <img class="mr-2 rounded" src="<%= gravatar_url(task.user, { size: 50 }) %>" alt="">
        <div class="media-body">
            <div>
                <span class="text-muted"><%= task.user.name %> <%= task.created_at %></span>
            </div>
            <div>
                <p><%= task.content %> <%= task.status %><%= link_to "Delete", task, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm float-right' %><%= link_to "詳細", task, class: 'btn btn-primary btn-sm float-right' %></p>
            </div>
        </div>
    </li>
    <% end %>
    <%= paginate tasks %>
</ul>

app/views/tasks/edit.html.erb
<h2 class="pb-4 pt-4">タスク内容変更</h2>

<div class="row">
    <div class = "col-sm-4">
<%= render "form", task: @task %>
</div>
</div>

app/views/tasks/index.html.erb
<p>ログイン完了ユーザ: <%= current_user.name %></p>

<h2 class="pb-4 pt-4">タスク一覧表</h2>
<div class="row">


    <div class="col-sm-8">
        <%= render 'tasks/tasks', tasks: @tasks %>
    </div>
</div>

app/views/tasks/new.html.erb
<h2 class="pb-4 pt-4">新規タスク</h2>
<div class="row">
    <div class = "col-sm-4">
<%= render "form", task: @task %>
</div>
</div>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> の詳細</h1>

<p><%= @task.content %></p>
<p><%= @task.status %></p>


<%= link_to '一覧に戻る', tasks_path %>
<%= link_to '編集する', edit_task_path(@task) %>

app/views/users/new.html.erb
<div class="text-center">
    <h1>SignUp</h1>
</div>

<div class="row">
    <div class="col-sm-6 offset-sm-3">
        <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>

        <div class="form-group">
            <%= f.label :name, "Name" %>
            <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :email, "Email" %>
            <%= f.email_field :email, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :password, "Password" %>
            <%= f.password_field :password, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>

        <%= f.submit "SignUP", class: "btn btn-primary btn-block" %>
        <% end %>
    </div>
</div>